{
 "title": "lighthouse_test",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Latest scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest SEO scores",
   "type": "bargauge",
   "description": "latest",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  s1.url,\n  s1.value AS seo_score,\n  s1.createdAt\nFROM\n  statistics s1\nINNER JOIN (\n  SELECT\n    url,\n    MAX(createdAt) AS maxCreatedAt\n  FROM\n    statistics\n  WHERE\n    name = 'category_seo_median'\n  GROUP BY\n    url\n) s2 ON s1.url = s2.url AND s1.createdAt = s2.maxCreatedAt\nWHERE\n  s1.name = 'category_seo_median';\n"
    }
   ]
  },
  {
   "title": "Latest Accessibility scores",
   "type": "bargauge",
   "description": "latest",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  s1.url,\n  s1.value AS a11y_score,\n  s1.createdAt\nFROM\n  statistics s1\nINNER JOIN (\n  SELECT\n    url,\n    MAX(createdAt) AS maxCreatedAt\n  FROM\n    statistics\n  WHERE\n    name = 'category_accessibility_median'\n  GROUP BY\n    url\n) s2 ON s1.url = s2.url AND s1.createdAt = s2.maxCreatedAt\nWHERE\n  s1.name = 'category_accessibility_median';\n"
    }
   ]
  },
  {
   "title": "Performance Score - Home Page (median)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ASIA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.asia.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS US_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.us.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS LATAM_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://tienda.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS UK_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.uk.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS EU_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.eu.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS FR_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.elsevier-masson.fr/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS DE_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://shop.elsevier.de/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS MEA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.mea.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ANZ_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://www.elsevierhealth.com.au/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS SP_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://tienda.elsevier.es/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS GLOBAL,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'category_performance_median' AND\n  statistics.url = 'https://shop.elsevier.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    }
   ]
  },
  {
   "title": "Performance Metrics - Home Page",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Speed Index (median)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ASIA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.asia.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS US_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.us.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS LATAM_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://tienda.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS UK_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.uk.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS EU_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.eu.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS FR_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.elsevier-masson.fr/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS DE_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://shop.elsevier.de/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS MEA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.mea.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ANZ_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://www.elsevierhealth.com.au/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS SP_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://tienda.elsevier.es/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS GLOBAL,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_speed-index_median' AND\n  statistics.url = 'https://shop.elsevier.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    }
   ]
  },
  {
   "title": "Time to Interactive (median)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ASIA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.asia.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS US_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.us.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS LATAM_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://tienda.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS UK_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.uk.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS EU_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.eu.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS FR_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.elsevier-masson.fr/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS DE_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://shop.elsevier.de/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS MEA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.mea.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ANZ_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://www.elsevierhealth.com.au/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS SP_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://tienda.elsevier.es/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS GLOBAL,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_interactive_median' AND\n  statistics.url = 'https://shop.elsevier.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (median)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ASIA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.asia.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS US_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.us.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS LATAM_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://tienda.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS UK_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.uk.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS EU_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.eu.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS FR_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.elsevier-masson.fr/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS DE_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://shop.elsevier.de/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS MEA_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.mea.elsevierhealth.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS ANZ_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://www.elsevierhealth.com.au/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS SP_HS,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://tienda.elsevier.es/'\nORDER BY\n  statistics.createdAt ASC;\n"
    },
    {
     "dataset": "lhci",
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(statistics.createdAt) AS time_sec,\n  statistics.value AS GLOBAL,\n  statistics.url AS metric\nFROM\n  statistics\nWHERE\n  statistics.name = 'audit_largest-contentful-paint_median' AND\n  statistics.url = 'https://shop.elsevier.com/'\nORDER BY\n  statistics.createdAt ASC;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "dataset": "lhci",
     "rawSql": "SELECT DISTINCT\n  name\nFROM\n  statistics\nORDER BY\n  name;\n"
    }
   ]
  }
 ]
}