name: Lighthouse CI

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
        run: npx lhci autorun
